# Generated by Django 4.2.5 on 2023-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.IntegerField(default=0, verbose_name='Thickness'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Width'),
        ),
    ]
