# Generated by Django 4.2.5 on 2023-09-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0003_buyer_seller_alter_product_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_nr', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Accepted'), ('p', 'In produce'), ('l', 'Loaded'), ('y', 'Delivered'), ('d', 'Declined')], default='a', max_length=1, verbose_name='Order Status')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bws.buyer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bws.product')),
            ],
        ),
    ]
