# Generated by Django 4.2.5 on 2023-09-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0004_buyerorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Buyer', 'verbose_name_plural': 'Buyers'},
        ),
        migrations.AlterModelOptions(
            name='buyerorder',
            options={'verbose_name': 'BuyerOrder', 'verbose_name_plural': 'BuyerOrders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AlterField(
            model_name='buyerorder',
            name='order_nr',
            field=models.CharField(default='BWS0001', max_length=10, unique=True),
        ),
    ]
