# Generated by Django 4.2.5 on 2023-09-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0005_alter_buyer_options_alter_buyerorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerorder',
            name='order_nr',
            field=models.CharField(blank=True, default='BWS0001', max_length=10, unique=True),
        ),
    ]
