# Generated by Django 4.2.5 on 2023-09-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0006_alter_buyerorder_order_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerorder',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='buyerorder',
            name='order_nr',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
