# Generated by Django 4.2.5 on 2023-09-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0007_buyerorder_quantity_alter_buyerorder_order_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerorder',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='SellerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_nr', models.CharField(blank=True, max_length=10, unique=True)),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bws.product')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bws.seller')),
            ],
            options={
                'verbose_name': 'SellerOrder',
                'verbose_name_plural': 'SellerOrders',
            },
        ),
    ]
