# Generated by Django 4.2.5 on 2023-09-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0008_remove_buyerorder_quantity_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorder',
            name='order_nr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bws.buyerorder'),
        ),
    ]
