# Generated by Django 4.2.5 on 2023-09-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0009_alter_sellerorder_order_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerorder',
            name='order_nr',
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='buyer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bws.buyerorder'),
        ),
    ]
