# Generated by Django 4.2.5 on 2023-09-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0010_remove_sellerorder_order_nr_sellerorder_buyer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerorder',
            name='product',
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='product2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bws.product'),
        ),
    ]
