# Generated by Django 4.2.5 on 2023-09-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0011_remove_sellerorder_product_sellerorder_product2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerorder',
            name='product2',
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='production_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bws.product', verbose_name='Production Product'),
        ),
    ]
