# Generated by Django 4.2.5 on 2023-09-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bws', '0012_remove_sellerorder_product2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerorder',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Accepted'), ('p', 'In produce'), ('l', 'Loaded'), ('y', 'Delivered'), ('d', 'Declined')], default='a', max_length=1, verbose_name='Order Status'),
        ),
    ]
